package Model.GameObjects;

public enum CardInGameState {
    IN_OUR_HAND , IN_OPPONENT_HAND , IN_OUR_FIELD , IN_OPPONENT_FIELD , IN_OUR_GRAVEYARD , IN_OPPONENT_GRAVEYARD
    , IN_OUR_FIELD_FLIPPED , IN_OUR_DECK;
}
